CONVERSATION_TIMEOUT = 600

FULL_NAME_MAX_LENGTH = 50

USERS_PAGINATION_LENGTH = 20

ACCOUNT_DEACTIVATE_REASON_MAX_LENGTH = 2000

DOWNGRADE_REASON_MAX_LENGTH = 2000

LESSONS_PAGINATION_LENGTH = 30

LESSON_TITLE_MAX_LENGTH = 50

QUESTION_TITLE_MAX_LENGTH = 50

QUESTION_TEXT_MAX_LENGTH = 3000

QUESTIONS_PAGINATION_LENGTH = 20

QUESTION_ATTACHMENT_MAX_NUMBER = 5

PICTURE_MAX_SIZE = 10

VIDEO_MAX_SIZE = 30

SOUND_MAX_SIZE = 5

ANSWER_QUESTION_MAX_NUMBER = 10

DELETE_ATTACHMENT_REASON_MAX_LENGTH = 2000
